server:
  port: 8080 # Port Number
  servlet: 
    encoding:
      charset: utf-8 # Servlet의 응답과 요청 인코딩을 UTF-8로 설정
      force: true # 요청과 응답에 대해 이 인코딩을 강제로 사용하도록 설정

spring:
  mvc:
    view: 
      prefix: /WEB-INF/view/ # JSP 파일이 위치한 디렉토리 접두사를 설정
      suffix: .jsp # 뷰 이름에 자동으로 추가될 파일 확장자를 설정
      
  datasource: 
    url: jdbc:h2:mem:bankdb;MODE=MySQL # 데이터 베이스 연결을 위한 URL 설정
    driver-class-name: org.h2.Driver # 드라이버 클래스를 설정
    username: sa # User ID
    password : '' # user Password 현재는 빈 문자열로 설정
    
  h2: 
    console:
      enabled: true # H2 Database Console 활성화
  
  output: 
    ansi:
      enabled: always # 콘솔 출력에 ANSI 색상 코드를 사용할 수 있도록 설정
      
#MyBatis 설정
mybatis: 
  mapper-locations: 
    - classpath:mapper/**/*.xml  #MyBatis 매퍼 파일 위치를 설정. '**'은 모든 디렉토리를 의미하며, '*.xml'은 모든 XML 파일을 의미한다. 
  configuration:
    map-underscore-to-camel-case: true # 데이터베이스의 언더스코어 네이밍(column_name)
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # SQL 로깅 구현체를 설정합니다.


logging: 
  level: 
    org.apache.ibatis: DEBUG #MyBatis 로깅 레벨을 DEBUG로 설정하여 실행되는 SQL 쿼리와 내부 로깅 정보를 콘솔에 출력한다. 